"""RBAC role literals — align with `users.role` in Supabase."""

STATE_AUTHORITY = "STATE_AUTHORITY"
DIVISIONAL_AUTHORITY = "DIVISIONAL_AUTHORITY"
DISTRICT_AUTHORITY = "DISTRICT_AUTHORITY"
TALUKA_AUTHORITY = "TALUKA_AUTHORITY"
CIRCLE_AUTHORITY = "CIRCLE_AUTHORITY"
VILLAGE_AUTHORITY = "VILLAGE_AUTHORITY"
TALATHI = "TALATHI"
KRUSHI_SAHAYAK = "KRUSHI_SAHAYAK"
KRUSHI_MITRA = "KRUSHI_MITRA"
FARMER = "FARMER"

ALL_ROLES = frozenset(
    {
        STATE_AUTHORITY,
        DIVISIONAL_AUTHORITY,
        DISTRICT_AUTHORITY,
        TALUKA_AUTHORITY,
        CIRCLE_AUTHORITY,
        VILLAGE_AUTHORITY,
        TALATHI,
        KRUSHI_SAHAYAK,
        KRUSHI_MITRA,
        FARMER,
    }
)

HIERARCHY_ROLES = frozenset(
    {
        STATE_AUTHORITY,
        DIVISIONAL_AUTHORITY,
        DISTRICT_AUTHORITY,
        TALUKA_AUTHORITY,
        CIRCLE_AUTHORITY,
        VILLAGE_AUTHORITY,
    }
)
